[project]
authors = ["wingerted <wingerted@gmail.com>"]
channels = ["conda-forge"]
description = "Conda package for nanoarrow"
name = "nanoarrow"
platforms = ["linux-64"]
version = "0.2.0"

[tasks]

[dependencies]
cmake = "*"
ninja = "*"
clang = "*"
clangxx = "*"
rattler-build = "*"
ccache = "*"
pip = ">=25.2,<26"
meson-python = ">=0.18.0,<0.19"
gcc = ">=15.1.0,<15.2"
gxx = ">=15.1.0,<15.2"
certifi = ">=2025.8.3,<2026"

[pypi-dependencies]
build = ">=1.3.0, <2"
