[project]
authors = ["wingerted <wingerted@gmail.com>"]
channels = ["conda-forge"]
description = "Conda package for nanoarrow"
name = "nanoarrow"
platforms = ["linux-64", "osx-arm64"]
version = "0.2.0"

[tasks]

[dependencies]
rattler-build = "*"
