context:
  version: 0.7.0

package:
  name: nanoarrow
  version: ${{ version }}

source:
  url: https://github.com/apache/arrow-nanoarrow/releases/download/apache-arrow-nanoarrow-${{ version }}/apache-arrow-nanoarrow-${{ version }}.tar.gz

build:
  script: build.sh
  number: 4

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
    - make
  host:
    - python
    - uv
    - cython
    - meson-python
    - setuptools >=61.0.0
  run: []

tests:
- python:
    imports:
    - nanoarrow
    - nanoarrow.ipc

# 包的元数据
about:
  homepage: https://github.com/apache/arrow-nanoarrow
  license: Apache-2.0
  summary: A minimal Arrow C data interface implementation
