package:
  name: nanoarrow
  version: 0.6.0

source:
  git: https://github.com/apache/arrow-nanoarrow.git
  tag: apache-arrow-nanoarrow-0.6.0

build:
  script: ./build.sh
  number: 1

requirements:
  build:
    - cmake
    - ninja
    - meson-python
    - gcc
    - gxx
  host:
    - python
    - pip
    - cython
    - setuptools
    - certifi
  run: []

# 包的元数据
about:
  homepage: https://github.com/apache/arrow-nanoarrow
  license: Apache-2.0
  summary: A minimal Arrow C data interface implementation
