context:
  version: 0.6.0

package:
  name: nanoarrow
  version: ${{ version }}

source:
  git: https://github.com/apache/arrow-nanoarrow.git
  tag: apache-arrow-nanoarrow-${{ version }}.dev

build:
  script: build.sh
  number: 2

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - uv
    - cython
    - setuptools >=61.0.0
  run: []

tests:
- python:
    imports:
    - nanoarrow

# 包的元数据
about:
  homepage: https://github.com/apache/arrow-nanoarrow
  license: Apache-2.0
  summary: A minimal Arrow C data interface implementation
